/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "viwcmiexjkjopijdzskw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpd2NtaWV4amtqb3BpamR6c2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5OTk3NDMsImV4cCI6MjA5MTU3NTc0M30.IdeszC3NQjHkF-Et7lm0KvUspZjTDEkWDd-T5lp-Q8k"